<a href="https://colab.research.google.com/github/rajnish80130/Real-state-Capstone-Project/blob/main/data_cleaning_level_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
import pandas as pd
import numpy as np

In [119]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [120]:
df = pd.read_csv('/content/gurgaon_properties.csv')
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,3.00,14285.0,2100.0,Super Built up area 2691(250 sq.m.)Built Up ar...,3,3,3+,servant room,"Sector 113 Gurgaon , Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,"['1 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Centrally Air Conditioned', 'Water purifier'...",NaN
1,3 BHK Flat in Sector 78 Gurgaon,flat,umang monsoon breeze,0.88,4746.0,1854.0,Super Built up area 1854(172.24 sq.m.)Built Up...,3,4,3,"pooja room,servant room","654, Sector 78 Gurgaon, Gurgaon, Haryana",8.0,North-West,5 to 10 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...",3 bhk flat available for sell in umang monsoon...,"['1 Wardrobe', '1 Stove', '1 Chimney', '1 Modu...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,4 BHK Flat in sector 58 Gurgaon,flat,ireo the grand arch,4.85,16934.0,2864.0,Carpet area: 2864 (266.07 sq.m.),4,5,3,"pooja room,study room,servant room,others","2304, sector 58 Gurgaon, Gurgaon, Haryana",23.0,North-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro', 'Paras Trinity Ma...",Check out this 4 bhk apartment for sale in ire...,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '6 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
3,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,1.49,6310.0,2361.0,Super Built up area 2361(219.34 sq.m.),3,4,3+,"servant room,store room","Dwarka Express Highway, Sector 107 Gurgaon, Gu...",5.0,East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Available 3 bhk plus servant room spacious apa...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction5 out ..."
4,4 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,6.16,20533.0,3000.0,Carpet area: 3000 (278.71 sq.m.),4,5,3+,"pooja room,servant room","Sector 22 Gurgaon, Gurgaon, Haryana",10.0,South-East,0 to 1 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Ambience creacions is one of gurgaon's most so...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [121]:
df.shape

(3955, 20)

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3955 entries, 0 to 3954
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3955 non-null   object
 1   property_type    3955 non-null   object
 2   society          3954 non-null   object
 3   price            3954 non-null   float64
 4   price_per_sqft   3954 non-null   float64
 5   area             3954 non-null   float64
 6   areaWithType     3955 non-null   object
 7   bedRoom          3955 non-null   int64
 8   bathroom         3955 non-null   int64
 9   balcony          3955 non-null   object
 10  additionalRoom   3955 non-null   object
 11  address          3944 non-null   object
 12  floorNum         3933 non-null   float64
 13  facing           2783 non-null   object
 14  agePossession    3954 non-null   object
 15  nearbyLocations  3749 non-null   object
 16  description      3955 non-null   object
 17  furnishDetails   2926 non-null   object
 18  features         3249 non-null   object
 19  rating           3506 non-null   object
dtypes: float64(4), int64(2), object(14)
memory usage: 618.1+ KB

In [123]:
df.duplicated().sum()

np.int64(13)

In [124]:
df[df.duplicated()]

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
836,8 Bedroom House for sale in Palam Vihar,house,Independent,5.60,17284.0,3240.0,Plot area 360(301.01 sq.m.),8,6,3+,"pooja room,study room,servant room,store room","Palam Vihar, Gurgaon, Haryana",NaN,South-West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",360 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Dining Table', '1 Light', '1 Modu...",NaN,"['Environment5 out of 5', 'Lifestyle5 out of 5..."
1316,12 Bedroom House for sale in DLF Phase 1,house,luxury dlf city floors,8.25,45833.0,1800.0,Plot area 200(167.23 sq.m.),12,12,3+,servant room,"A Block Dlf-1, DLF Phase 1, Gurgaon, Haryana",4.0,North,0 to 1 Year Old,"['Sikandarpur metro station', 'Sikanderpur met...",For sale brand new building having stilt and 4...,"['20 Fan', '1 Exhaust Fan', '12 Geyser', '40 L...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
2135,3 Bedroom House for sale in Sector 48 Gurgaon,house,vipul tatvam villa,7.25,27971.0,2592.0,Plot area 288(240.8 sq.m.),3,4,2,"servant room,study room,store room,pooja room","A111, Sector 48 Gurgaon, Gurgaon, Haryana",2.0,South,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Sector 48 gurgaon is one of gurgaon's most sou...,"['4 Wardrobe', '1 Water Purifier', '12 Fan', '...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2385,4 Bedroom House for sale in Sector 55 Gurgaon,house,Independent,3.55,24500.0,1449.0,Plot area 161(134.62 sq.m.),4,4,3+,na,"Sector 55 Gurgaon, Gurgaon, Haryana",2.0,NaN,10+ Year Old,"['Sector metro station', 'Sector metro station...",For sale 161yd independent house sector 55 gur...,"['6 Wardrobe', '9 Fan', '6 Geyser', '17 Light'...","['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2538,3 Bedroom House for sale in Palam Vihar,house,Independent,2.55,16378.0,1557.0,Plot area 173(144.65 sq.m.),3,3,2,na,"Palam Vihar, Gurgaon, Haryana",2.0,South,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",173 sq. Yards plot area near by global foyer m...,"['1 Fan', '1 Light', 'No AC', 'No Bed', 'No Ch...",['Park'],"['Environment5 out of 5', 'Lifestyle5 out of 5..."
3197,4 Bedroom House for sale in Sector 112 Gurgaon,house,experion windchants,7.99,12519.0,6382.0,Built Up area: 6382 (592.91 sq.m.),4,6,3,"servant room,store room,pooja room","Wp1- Wp-8, Sector 112 Gurgaon, Gurgaon, Haryana",2.0,South-East,0 to 1 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...",Available for sale 4bhk + servant luxury villa...,"['1 Exhaust Fan', '7 Geyser', '1 Stove', '10 A...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3215,6 Bedroom House for sale in Uppals Southend,house,uppal southend,3.75,25562.0,1467.0,Plot area 163(136.29 sq.m.),6,6,3,others,"Uppals Southend, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['Sri Radhe Krishna Temple', 'Icici bank ATM',...",Address...Uppal southend sector 49 w blook \n6...,NaN,"['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3302,4 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.40,20690.0,2610.0,Plot area 290(242.48 sq.m.),4,5,3+,"pooja room,store room,study room,servant room","290 Sqyd Duplex Villa, Sector 70A Gurgaon, Gur...",3.0,North,1 to 5 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...","Bptp duplex villa 290 sqyd plot size, private ...","['5 Wardrobe', '1 Water Purifier', '6 Geyser',...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
3303,5 Bedroom House for sale in Greenwood City,house,Independent,17.00,37777.0,4500.0,Plot area 4500(418.06 sq.m.),5,8,3+,"pooja room,study room,servant room,store room","0000, Greenwood City, Gurgaon, Haryana",3.0,North-East,1 to 5 Year Old,"['Huda city centre metro station', 'Axis bank ...",Ultra luxury kothi for sale in greenwood city ...,"['1 Water Purifier', '11 Fan', '1 Fridge', '1 ...","['Centrally Air Conditioned', 'Water purifier'...","['Environment4.5 out of 5', 'Lifestyle4 out of..."
3534,4 Bedroom House for sale in C Block Sushant Lo...,house,Independent,5.75,29716.0,1935.0,Plot area 215(179.77 sq.m.),4,4,2,"servant room,pooja room,store room","C Block Sushant Lok Phase 1, Gurgaon, Haryana",2.0,North,10+ Year Old,"['Sector 42-43 metro station', 'Huda city cent...",North facing property\n100 meter from vaipar k...,NaN,"['Feng Shui / Vaastu Compliant', 'High Ceiling...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3829,4 Bedroom House for sale in Sector 91 Gurgaon,house,dlf new town heights,2.50,7058.0,3542.0,Plot area 3400(315.87 sq.m.),4,4,3+,"pooja room,study room,servant room,store room","Sector 91 Gurgaon, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['MG Road Metro Station', 'RHM Public School',...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '9 Fan', '1 Exhaust Fa...","['Feng Shui / Vaastu Compliant', 'Maintenance ...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
3895,4 Bedroom House for sale in Sector 86 Gurgaon,house,dlf new town heights,2.50,7058.0,3542.0,Plot area 3400(315.87 sq.m.),4,4,3+,"study room,servant room,pooja room,store room","Sector 86 Gurgaon, Gurgaon, Haryana",3.0,East,5 to 10 Year Old,"['City Square', 'Vatika Town Square', 'Bharat ...","Dlf new town heights, 4bhk independent villa a...","['2 Bed', '7 Wardrobe', '12 Fan', '1 Exhaust F...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3935,4 Bedroom House for sale in Sector 48 Gurgaon,house,vipul tatvam villa,8.40,21000.0,4000.0,Plot area 4000(371.61 sq.m.),4,5,3+,"pooja room,study room,servant room","Sector 48 Gurgaon, Gurgaon, Haryana",2.0,North,5 to 10 Year Old,"['Athena', 'Star Mall', 'The Sixth Element Sch...",Wishing to settle down in an individual house ...,"['5 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [125]:
df.isnull().sum()

property_name         0
property_type         0
society               1
price                 1
price_per_sqft        1
area                  1
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom        0
address              11
floorNum             22
facing             1172
agePossession         1
nearbyLocations     206
description           0
furnishDetails     1029
features            706
rating              449
dtype: int64

In [126]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,3.00,14285.0,2100.0,Super Built up area 2691(250 sq.m.)Built Up ar...,3,3,3+,servant room,"Sector 113 Gurgaon , Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,"['1 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Centrally Air Conditioned', 'Water purifier'...",NaN
1,3 BHK Flat in Sector 78 Gurgaon,flat,umang monsoon breeze,0.88,4746.0,1854.0,Super Built up area 1854(172.24 sq.m.)Built Up...,3,4,3,"pooja room,servant room","654, Sector 78 Gurgaon, Gurgaon, Haryana",8.0,North-West,5 to 10 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...",3 bhk flat available for sell in umang monsoon...,"['1 Wardrobe', '1 Stove', '1 Chimney', '1 Modu...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,4 BHK Flat in sector 58 Gurgaon,flat,ireo the grand arch,4.85,16934.0,2864.0,Carpet area: 2864 (266.07 sq.m.),4,5,3,"pooja room,study room,servant room,others","2304, sector 58 Gurgaon, Gurgaon, Haryana",23.0,North-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro', 'Paras Trinity Ma...",Check out this 4 bhk apartment for sale in ire...,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '6 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
3,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,1.49,6310.0,2361.0,Super Built up area 2361(219.34 sq.m.),3,4,3+,"servant room,store room","Dwarka Express Highway, Sector 107 Gurgaon, Gu...",5.0,East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Available 3 bhk plus servant room spacious apa...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction5 out ..."
4,4 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,6.16,20533.0,3000.0,Carpet area: 3000 (278.71 sq.m.),4,5,3+,"pooja room,servant room","Sector 22 Gurgaon, Gurgaon, Haryana",10.0,South-East,0 to 1 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Ambience creacions is one of gurgaon's most so...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [127]:
df.insert(loc=3,column='sector',value=df['property_name'].str.split('in').str.get(1).str.replace('Gurgaon','').str.strip())

In [128]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,Sector 113,3.00,14285.0,2100.0,Super Built up area 2691(250 sq.m.)Built Up ar...,3,3,3+,servant room,"Sector 113 Gurgaon , Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,"['1 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Centrally Air Conditioned', 'Water purifier'...",NaN
1,3 BHK Flat in Sector 78 Gurgaon,flat,umang monsoon breeze,Sector 78,0.88,4746.0,1854.0,Super Built up area 1854(172.24 sq.m.)Built Up...,3,4,3,"pooja room,servant room","654, Sector 78 Gurgaon, Gurgaon, Haryana",8.0,North-West,5 to 10 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...",3 bhk flat available for sell in umang monsoon...,"['1 Wardrobe', '1 Stove', '1 Chimney', '1 Modu...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,4 BHK Flat in sector 58 Gurgaon,flat,ireo the grand arch,sector 58,4.85,16934.0,2864.0,Carpet area: 2864 (266.07 sq.m.),4,5,3,"pooja room,study room,servant room,others","2304, sector 58 Gurgaon, Gurgaon, Haryana",23.0,North-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro', 'Paras Trinity Ma...",Check out this 4 bhk apartment for sale in ire...,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '6 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
3,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,Sector 107,1.49,6310.0,2361.0,Super Built up area 2361(219.34 sq.m.),3,4,3+,"servant room,store room","Dwarka Express Highway, Sector 107 Gurgaon, Gu...",5.0,East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Available 3 bhk plus servant room spacious apa...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction5 out ..."
4,4 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,Sector 22,6.16,20533.0,3000.0,Carpet area: 3000 (278.71 sq.m.),4,5,3+,"pooja room,servant room","Sector 22 Gurgaon, Gurgaon, Haryana",10.0,South-East,0 to 1 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Ambience creacions is one of gurgaon's most so...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [129]:
df['sector'] = df['sector'].str.lower()

In [130]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,sector 113,3.00,14285.0,2100.0,Super Built up area 2691(250 sq.m.)Built Up ar...,3,3,3+,servant room,"Sector 113 Gurgaon , Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,"['1 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Centrally Air Conditioned', 'Water purifier'...",NaN
1,3 BHK Flat in Sector 78 Gurgaon,flat,umang monsoon breeze,sector 78,0.88,4746.0,1854.0,Super Built up area 1854(172.24 sq.m.)Built Up...,3,4,3,"pooja room,servant room","654, Sector 78 Gurgaon, Gurgaon, Haryana",8.0,North-West,5 to 10 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...",3 bhk flat available for sell in umang monsoon...,"['1 Wardrobe', '1 Stove', '1 Chimney', '1 Modu...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,4 BHK Flat in sector 58 Gurgaon,flat,ireo the grand arch,sector 58,4.85,16934.0,2864.0,Carpet area: 2864 (266.07 sq.m.),4,5,3,"pooja room,study room,servant room,others","2304, sector 58 Gurgaon, Gurgaon, Haryana",23.0,North-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro', 'Paras Trinity Ma...",Check out this 4 bhk apartment for sale in ire...,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '6 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
3,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,sector 107,1.49,6310.0,2361.0,Super Built up area 2361(219.34 sq.m.),3,4,3+,"servant room,store room","Dwarka Express Highway, Sector 107 Gurgaon, Gu...",5.0,East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Available 3 bhk plus servant room spacious apa...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction5 out ..."
4,4 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,sector 22,6.16,20533.0,3000.0,Carpet area: 3000 (278.71 sq.m.),4,5,3+,"pooja room,servant room","Sector 22 Gurgaon, Gurgaon, Haryana",10.0,South-East,0 to 1 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Ambience creacions is one of gurgaon's most so...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [131]:
df['sector'].value_counts()

sector
sohna                                                        163
sector 102                                                   113
sector 85                                                    110
sector 92                                                    104
sector 69                                                     94
sector 65                                                     90
sector 90                                                     90
sector 81                                                     90
sector 109                                                    88
sector 79                                                     80
sector 83                                                     69
sector 86                                                     68
sector 37d                                                    68
sector 104                                                    66
sector 107                                                    60
sector 108                                                    58
sector 48                                                     58
sector 95                                                     57
sector 56                                                     57
sector 89                                                     56
sector 70a                                                    55
sector 70                                                     53
sector 37c                                                    53
nirvana country                                               52
palam vihar                                                   52
sector-33 sohna                                               51
sector 84                                                     51
sector 67                                                     48
sector 103                                                    45
dlf phase 1                                                   44
sector 113                                                    43
sector 61                                                     42
sector 66                                                     42
sector 82                                                     42
dlf phase 2                                                   41
sector 106                                                    38
sector 49                                                     36
sector 99a                                                    32
sushant lok phase 1                                           31
sector 68                                                     30
sector 77                                                     29
sector 72                                                     29
sector 71                                                     27
sector 54                                                     27
laxman vihar                                                  26
dlf phase 4                                                   25
sector 112                                                    25
sector 88a                                                    23
sector 67a                                                    22
sector 111                                                    22
dlf phase 3                                                   21
sector 33                                                     20
sector 22                                                     20
sector 82a                                                    20
sector 78                                                     19
sector 63a                                                    18
sector 74                                                     18
sector 91                                                     18
sector 62                                                     17
sushant lok phase 3                                           16
sector 110                                                    16
sector 99                                                     16
sector 60                                                     15
sector 14                                                     15
sector 63                                                     15
gwal pahari                                                   14
sector 53                                                     14
sector 3                                                      14
sector 1 imt manesar                                          14
rajendra park                                                 14
dlf phase 5                                                   14
sector 76                                                     14
sector 52                                                     14
laxman vihar phase 2                                          13
uppals southend                                               13
sector 46                                                     13
sector 36a                                                    13
sector 50                                                     12
sector 39                                                     12
sector 31                                                     12
sector 93                                                     12
sohna road                                                    12
sector 38                                                     12
ashok vihar phase 3 extension                                 11
sector 9a                                                     11
sector 47                                                     11
sector 7                                                      10
sector 1a imt manesar                                         10
sector 55                                                     10
c block sushant lok phase 1                                    9
south city 1                                                   9
ashok vihar phase 2                                            9
sector 95a                                                     9
sector 4                                                       9
malibu town                                                    8
sector 43                                                      8
palam vihar extension                                          8
sector 10a                                                     8
mehrauli  road                                                 8
sector 57                                                      8
dwarka expressway                                              8
sector 40                                                      8
sector 89 a                                                    8
sector 59                                                      8
new colony                                                     7
mianwali colony                                                7
surat nagar 1                                                  7
sector 51                                                      7
sector 26                                                      7
sector 36 sohna                                                7
sector 58                                                      7
sector 1                                                       6
sector 5                                                       6
jacobpura                                                      6
jyoti park                                                     6
sector 11                                                      6
rajiv nagar                                                    6
greenwood city                                                 6
ashok vihar                                                    6
new palam vihar                                                5
subhash nagar                                                  5
sector 2                                                       5
saraswati vihar                                                5
sector 105                                                     5
ansal plaza                                                    5
dayanand colony                                                5
sector 80                                                      5
sector 9                                                       5
sector 30                                                      5
sushant lok phase 2                                            5
manesar                                                        5
chakkarpur                                                     5
sector 23a                                                     5
arjun nagar                                                    5
sector 28                                                      5
shivpuri                                                       4
sector 6                                                       4
madanpuri                                                      4
ravi nagar                                                     4
garhi harsaru                                                  4
surya vihar                                                    4
adarsh nagar                                                   4
new                                                            4
shivaji nagar                                                  4
sector 12                                                      4
dharam colony                                                  4
vishnu garden                                                  4
sector 36                                                      4
imt manesar                                                    4
sector 3a                                                      4
bhondsi                                                        4
sector 12a                                                     4
baldev nagar                                                   4
devilal colony                                                 4
suncity                                                        4
valley view estate                                             4
krishna colony                                                 4
bhim nagar                                                     4
sector 17                                                      4
sector 88b                                                     3
mg road                                                        3
patel nagar                                                    3
sector 15                                                      3
sector 110 a                                                   3
laxmi garden                                                   3
sector 73                                                      3
b block sushant lok phase 1                                    3
prem nagar                                                     3
sector 27                                                      3
sector 17a                                                     3
a block sushant lok phase 1                                    3
gandhi nagar                                                   3
sector 8                                                       3
sector 45                                                      3
sector 23                                                      3
maruti kunj                                                    3
sector 17b                                                     3
new palam vihar phase 1                                        2
sector 15 part 2                                               2
shanti nagar                                                   2
sushant lok                                                    2
block a surya vihar                                            2
sector-2 sohna                                                 2
sohna  road                                                    2
surat nagar                                                    2
sector 24                                                      2
surat nagar phase 2                                            2
rajiv chowk                                                    2
sector 41                                                      2
golf course ext road                                           2
samaspur                                                       2
, delhi ncr                                                    2
new basti                                                      2
shakti nagar                                                   2
golf course road                                               2
lajpat nagar                                                   2
sispal vihar                                                   2
sector 21                                                      2
pratap nagar                                                   2
nars                                                           2
iffco chowk                                                    2
farukhnagar                                                    2
faridabad road                                                 2
sector 15 part 1                                               2
shankar vihar                                                  2
hira nagar                                                     2
rosewood                                                       2
mohan nagar                                                    2
sector 32                                                      2
mayfield garden                                                2
west rajiv nagar                                               2
ambience island                                                2
sheetla colony                                                 2
daulatabad                                                     2
new palam vihar phase 2                                        2
manohar nagar                                                  2
bhawani enclave                                                2
bissar                                                         2
sector-11 sohna                                                2
acharya puri                                                   2
cyber city                                                     1
bhora kalan                                                    1
block h ashok vihar phase iii extension                        1
jat colony,fazilpur/taj nagar road                             1
heritage city                                                  1
dhankot                                                        1
sector-7 hous                                                  1
laxman vihar, railway road,                                    1
huda saraswati vihar                                           1
sector 5 chowk                                                 1
rattan garden                                                  1
near nand hospital                                             1
ashok vihar phase i                                            1
pataudi road                                                   1
sultanpur                                                      1
hno 13 sagar enclave sura                                      1
park view                                                      1
saraswati enclave                                              1
sector-35 sohna                                                1
tekchand nagar                                                 1
ashok vihar phase 3                                            1
godrej aria , sector 79 ,                                      1
ansal's palam vihar                                            1
jacobpura near sadar bazar                                     1
damdma                                                         1
nirvana country pocket h                                       1
kheri                                                          1
ravi nager basai road                                          1
shivji park colony                                             1
garauli kalan                                                  1
om nagar                                                       1
kanahi                                                         1
vir nagar                                                      1
rajiv colony                                                   1
near euro                                                      1
new jyoti park                                                 1
b1 block sector 57                                             1
sai kunj                                                       1
south city                                                     1
ats marigold                                                   1
sector 21a faridabad                                           1
ram nagar                                                      1
sector 4 urban estate                                          1
hsiidc plot sector 1 imt manesar                               1
part 3 sector 5                                                1
civil l                                                        1
near khandsa road                                              1
new colony, sector 7                                           1
sector-5 sheetla colony                                        1
sector 37b                                                     1
begampur khatola                                               1
khandsa                                                        1
carterpuri village                                             1
mahavir pura                                                   1
near sector 1 market                                           1
urban estate, sector 5                                         1
mahalaxmi garden, rajendra place                               1
sector-5 sohna                                                 1
sector 37a                                                     1
near pataudi chowk                                             1
laxmna vihar, phase 2                                          1
saroop garden rajendra park                                    1
devi lal colony gali no 12 gurgaon nr omkar public school      1
lucknow                                                        1
old delhi road, opp sector-14                                  1
alipur                                                         1
bhimgarh kheri phase 3                                         1
g block dlf city phase 1                                       1
sector 42                                                      1
anand garden, sector-105                                       1
sadar bazar                                                    1
gopal nagar, garhi ghasita, sonipat                            1
v block dlf phase 3                                            1
sector 13                                                      1
block g sector-57                                              1
sector 9b                                                      1
sector 17c                                                     1
bptp                                                           1
sec 3 bhim vihar part 1 bhimgher kheri                         1
Name: count, dtype: int64

In [132]:
df['sector'] = df['sector'].str.replace('dharam colony','sector 12')
df['sector'] = df['sector'].str.replace('krishna colony','sector 7')
df['sector'] = df['sector'].str.replace('suncity','sector 54')
df['sector'] = df['sector'].str.replace('prem nagar','sector 13')
df['sector'] = df['sector'].str.replace('mg road','sector 28')
df['sector'] = df['sector'].str.replace('gandhi nagar','sector 28')
df['sector'] = df['sector'].str.replace('laxmi garden','sector 11')
df['sector'] = df['sector'].str.replace('shakti nagar','sector 11')

In [133]:
df['sector'] = df['sector'].str.replace('baldev nagar','sector 7')
df['sector'] = df['sector'].str.replace('shivpuri','sector 7')
df['sector'] = df['sector'].str.replace('garhi harsaru','sector 17')
df['sector'] = df['sector'].str.replace('imt manesar','manesar')
df['sector'] = df['sector'].str.replace('adarsh nagar','sector 12')
df['sector'] = df['sector'].str.replace('shivaji nagar','sector 11')
df['sector'] = df['sector'].str.replace('bhim nagar','sector 6')
df['sector'] = df['sector'].str.replace('madanpuri','sector 7')

In [134]:
df['sector'] = df['sector'].str.replace('saraswati vihar','sector 28')
df['sector'] = df['sector'].str.replace('arjun nagar','sector 8')
df['sector'] = df['sector'].str.replace('ravi nagar','sector 9')
df['sector'] = df['sector'].str.replace('vishnu garden','sector 105')
df['sector'] = df['sector'].str.replace('bhondsi','sector 11')
df['sector'] = df['sector'].str.replace('surya vihar','sector 21')
df['sector'] = df['sector'].str.replace('devilal colony','sector 9')
df['sector'] = df['sector'].str.replace('valley view estate','gwal pahari')

In [135]:
df['sector'] = df['sector'].str.replace('mehrauli  road','sector 14')
df['sector'] = df['sector'].str.replace('jyoti park','sector 7')
df['sector'] = df['sector'].str.replace('ansal plaza','sector 23')
df['sector'] = df['sector'].str.replace('dayanand colony','sector 6')
df['sector'] = df['sector'].str.replace('sushant lok phase 2','sector 55')
df['sector'] = df['sector'].str.replace('chakkarpur','sector 28')
df['sector'] = df['sector'].str.replace('greenwood city','sector 45')
df['sector'] = df['sector'].str.replace('subhash nagar','sector 12')

In [136]:
df['sector'] = df['sector'].str.replace('sohna road road','sohna road')
df['sector'] = df['sector'].str.replace('malibu town','sector 47')
df['sector'] = df['sector'].str.replace('surat nagar 1','sector 104')
df['sector'] = df['sector'].str.replace('new colony','sector 7')
df['sector'] = df['sector'].str.replace('mianwali colony','sector 12')
df['sector'] = df['sector'].str.replace('jacobpura','sector 12')
df['sector'] = df['sector'].str.replace('rajiv nagar','sector 13')
df['sector'] = df['sector'].str.replace('ashok vihar','sector 3')

In [137]:
df['sector'] = df['sector'].str.replace('dlf phase 1','sector 26')
df['sector'] = df['sector'].str.replace('nirvana country','sector 50')
df['sector'] = df['sector'].str.replace('palam vihar','sector 2')
df['sector'] = df['sector'].str.replace('dlf phase 2','sector 25')
df['sector'] = df['sector'].str.replace('sushant lok phase 1','sector 43')
df['sector'] = df['sector'].str.replace('laxman vihar','sector 4')
df['sector'] = df['sector'].str.replace('dlf phase 4','sector 28')
df['sector'] = df['sector'].str.replace('dlf phase 3','sector 24')

In [138]:
df['sector'] = df['sector'].str.replace('sushant lok phase 3','sector 57')
df['sector'] = df['sector'].str.replace('dlf phase 5','sector 43')
df['sector'] = df['sector'].str.replace('rajendra park','sector 105')
df['sector'] = df['sector'].str.replace('uppals southend','sector 49')
df['sector'] = df['sector'].str.replace('sohna','sohna road')
df['sector'] = df['sector'].str.replace('ashok vihar phase 3 extension','sector 5')
df['sector'] = df['sector'].str.replace('south city 1','sector 41')
df['sector'] = df['sector'].str.replace('ashok vihar phase 2','sector 5')

In [139]:
a = df['sector'].value_counts()[df['sector'].value_counts() >= 3]
df = df[df['sector'].isin(a.index)]

In [140]:
df['sector'].value_counts()

sector
sohna road                    163
sector 102                    113
sector 85                     110
sector 92                     104
sector 69                      94
sector 90                      90
sector 65                      90
sector 81                      90
sector 109                     88
sector 79                      80
sector 104                     73
sector 83                      69
sector 86                      68
sector 37d                     68
sector 50                      64
sector 107                     60
sector 48                      58
sector 108                     58
sector 2                       57
sector 56                      57
sector 95                      57
sector 89                      56
sector 70a                     55
sector 43                      53
sector 37c                     53
sector 70                      53
sector 26                      51
sector 84                      51
sector-33 sohna road           51
sector 49                      49
sector 67                      48
sector 28                      46
sector 103                     45
sector 113                     43
sector 66                      42
sector 61                      42
sector 82                      42
sector 25                      41
sector 7                       39
sector 106                     38
sector 4                       35
sector 99a                     32
sector 54                      31
sector 68                      30
sector 12                      30
sector 72                      29
sector 77                      29
sector 71                      27
sector 112                     25
sector 57                      24
sector 105                     23
sector 88a                     23
sector 24                      23
sector 14                      23
sector 67a                     22
sector 111                     22
sector 22                      20
sector 82a                     20
sector 3                       20
sector 33                      20
sector 78                      19
sector 11                      19
sector 47                      19
sector 91                      18
sector 74                      18
sector 63a                     18
gwal pahari                    18
sector 62                      17
sector 110                     16
sector 99                      16
sector 63                      15
sector 55                      15
sector 60                      15
sector 52                      14
sector 1 manesar               14
sector 76                      14
sector 53                      14
sector 4 phase 2               13
sector 9                       13
sector 36a                     13
sector 46                      13
sector 6                       13
sector 39                      12
sohna road road                12
sector 38                      12
sector 31                      12
sector 93                      12
sector 9a                      11
sector 41                      11
sector 3 phase 3 extension     11
sector 1a manesar              10
sector 13                      10
c block sector 43               9
sector 45                       9
sector 3 phase 2                9
manesar                         9
sector 95a                      9
sector 89 a                     8
sector 10a                      8
sector 8                        8
sector 2 extension              8
dwarka expressway               8
sector 40                       8
sector 59                       8
sector 17                       8
sector 23                       8
sector 58                       7
sector 36 sohna road            7
sector 51                       7
sector 1                        6
sector 21                       6
sector 5                        6
sector 80                       5
sector 30                       5
new sector 2                    5
sector 23a                      5
sector 12a                      4
sector 3a                       4
sector 36                       4
new                             4
patel nagar                     3
sector 110 a                    3
b block sector 43               3
sector 73                       3
sector 88b                      3
maruti kunj                     3
sector 15                       3
a block sector 43               3
sector 17b                      3
sector 17a                      3
sector 27                       3
Name: count, dtype: int64

In [146]:
df['sector'] = df['sector'].str.replace('sector 95a','sector 95')
df['sector'] = df['sector'].str.replace('sector 23a','sector 23')
df['sector'] = df['sector'].str.replace('sector 12a','sector 12')
df['sector'] = df['sector'].str.replace('sector 3a','sector 3')
df['sector'] = df['sector'].str.replace('sector 110 a','sector 110')
df['sector'] = df['sector'].str.replace('patel nagar','sector 15')
df['sector'] = df['sector'].str.replace('a block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('maruti kunj','sector 12')
df['sector'] = df['sector'].str.replace('b block sector 43','sector 43')

In [147]:
df['sector'] = df['sector'].str.replace('sector-33 sohna road','sector 33')
df['sector'] = df['sector'].str.replace('sector 1 manesar','manesar')
df['sector'] = df['sector'].str.replace('sector 4 phase 2','sector 4')
df['sector'] = df['sector'].str.replace('sector 1a manesar','manesar')
df['sector'] = df['sector'].str.replace('c block sector 43','sector 43')
df['sector'] = df['sector'].str.replace('sector 89 a','sector 89')
df['sector'] = df['sector'].str.replace('sector 2 extension','sector 2')
df['sector'] = df['sector'].str.replace('sector 36 sohna road','sector 36')

In [143]:
df[df['sector'] == 'new']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
732,2 BHK Flat in New Gurgaon,flat,green court,new,0.38,5507.0,690.0,Carpet area: 690 (64.1 sq.m.),2,2,1,not availble,"New Gurgaon, Gurgaon, Haryana",7.0,NaN,Under Construction,"['Ing bank ATM', 'Dcb bank ATM', 'Indus ind ba...",We are the proud owners of this 2 bhk apartmen...,[],"['Intercom Facility', 'Lift(s)', 'Maintenance ...",NaN
2457,4 BHK Flat in New Gurgaon,flat,dlf 76,new,4.00,11428.0,3500.0,Carpet area: 3500 (325.16 sq.m.),4,4,2,"study room,servant room","New Gurgaon, Gurgaon, Haryana",4.0,NaN,Jun-27,"['Shri Balaji Hospital and Trauma Center', 'S....",This lovely 4 bhk apartment/flat in new gurgao...,"['6 Wardrobe', '1 Fridge', '8 Fan', '1 Exhaust...","['Security / Fire Alarm', 'Feng Shui / Vaastu ...",NaN
2577,4 BHK Flat in New Gurgaon,flat,sare homes,new,0.85,4786.0,1776.0,Super Built up area 1776(165 sq.m.),4,4,3,not availble,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,5 to 10 Year Old,"['Columbia Asia Hospital', 'Apex Multi Special...",Located in the popular residential address of ...,[],NaN,NaN
3217,2 BHK Flat in New Gurgaon,flat,takshila heights sector 37 c,new,0.67,5583.0,1200.0,Super Built up area 1200(111.48 sq.m.),2,2,2,not availble,"New Gurgaon, Gurgaon, Haryana",3.0,NaN,1 to 5 Year Old,"['Shri Balaji Hospital and Trauma Center', 'S....",Check out this 2 bhk apartment for sale in tak...,[],"['Lift(s)', 'Swimming Pool', 'Visitor Parking'...",NaN

In [144]:
df.loc[3217,'sector'] = 'sector 37'
df.loc[2577,'sector'] = 'sector 92'
df.loc[732,'sector'] = 'sector 90'
df.loc[2457,'sector'] = 'sector 76'

In [145]:
df[df['sector'] == 'new sector 2']

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
509,2 Bedroom House for sale in New Palam Vihar,house,my home,new sector 2,0.34,12592.0,270.0,Plot area 270(25.08 sq.m.),2,2,2,na,"Ez-19 A, New Palam Vihar, Gurgaon, Haryana",3.0,West,5 to 10 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",There are availability of various facilities l...,"['1 Wardrobe', '3 Fan', '6 Light', 'No AC', 'N...","['Water Storage', 'Park', 'Visitor Parking']","['Environment4 out of 5', 'Lifestyle4 out of 5..."
1697,2 BHK Flat in New Palam Vihar,flat,ompee k s residency,new sector 2,1.60,26936.0,594.0,Carpet area: 66 (55.18 sq.m.),2,2,2,not availble,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",We are the proud owners of this 2 bhk apartmen...,NaN,NaN,"['Environment4 out of 5', 'Safety4 out of 5', ..."
2926,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.22,4400.0,500.0,Carpet area: 500 (46.45 sq.m.),2,2,1,not availble,"New Palam Vihar, Gurgaon, Haryana",1.0,NaN,0 to 1 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...",Cctv surveillance are provided here. There is ...,"['3 Fan', '1 Exhaust Fan', '15 Light', '1 Modu...",NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."
3046,3 Bedroom House for sale in New Palam Vihar,house,Independent,new sector 2,1.00,8796.0,1137.0,Plot area 120(100.34 sq.m.)Built Up area: 120 ...,3,2,2,pooja room,"Q-148, New Palam Vihar, Phase-2, Near Royal Oa...",1.0,North,10+ Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","Ground and first floor, Ground floor: Ground f...",NaN,NaN,"['Environment4 out of 5', 'Lifestyle4 out of 5..."
3714,2 BHK Flat in New Palam Vihar,flat,my home,new sector 2,0.28,3166.0,884.0,Carpet area: 900 (83.61 sq.m.),2,1,1,others,"F 150/b, New Palam Vihar, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Palam Vihar Vyapar kendra', 'Palam triangle'...","2 bhk room with wooden coverd ,1 drawing room,...","['3 Wardrobe', '5 Light', '1 Chimney', '1 Modu...","['Water Storage', 'Park']","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [148]:
df['sector'] = df['sector'].str.replace('new sector 2','sector 110')

In [150]:
df.shape

(3799, 21)

In [151]:
df.duplicated().sum()

np.int64(13)

In [152]:
df.head()

,property_name,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,3 BHK Flat in Sector 113 Gurgaon,flat,la vida by tata housing,sector 113,3.00,14285.0,2100.0,Super Built up area 2691(250 sq.m.)Built Up ar...,3,3,3+,servant room,"Sector 113 Gurgaon , Gurgaon, Haryana",3.0,East,1 to 5 Year Old,"['Dwarka Sector 21', 'Pacific D21 Mall', 'Bajg...",La vida by tata housing is one of the most pop...,"['1 AC', 'No Bed', 'No Chimney', 'No Curtains'...","['Centrally Air Conditioned', 'Water purifier'...",NaN
1,3 BHK Flat in Sector 78 Gurgaon,flat,umang monsoon breeze,sector 78,0.88,4746.0,1854.0,Super Built up area 1854(172.24 sq.m.)Built Up...,3,4,3,"pooja room,servant room","654, Sector 78 Gurgaon, Gurgaon, Haryana",8.0,North-West,5 to 10 Year Old,"['Proposed Metro Station', 'Mahapal Shing', 'N...",3 bhk flat available for sell in umang monsoon...,"['1 Wardrobe', '1 Stove', '1 Chimney', '1 Modu...","['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Environment4 out of 5', 'Lifestyle4 out of 5..."
2,4 BHK Flat in sector 58 Gurgaon,flat,ireo the grand arch,sector 58,4.85,16934.0,2864.0,Carpet area: 2864 (266.07 sq.m.),4,5,3,"pooja room,study room,servant room,others","2304, sector 58 Gurgaon, Gurgaon, Haryana",23.0,North-West,1 to 5 Year Old,"['Sector 55-56 Rapid Metro', 'Paras Trinity Ma...",Check out this 4 bhk apartment for sale in ire...,"['4 Wardrobe', '4 Fan', '1 Exhaust Fan', '6 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of..."
3,3 BHK Flat in Sector 107 Gurgaon,flat,m3m woodshire,sector 107,1.49,6310.0,2361.0,Super Built up area 2361(219.34 sq.m.),3,4,3+,"servant room,store room","Dwarka Express Highway, Sector 107 Gurgaon, Gu...",5.0,East,1 to 5 Year Old,"['Signum 107', 'Nora Solomon Medicenter', 'Ind...",Available 3 bhk plus servant room spacious apa...,"['3 Wardrobe', '7 Fan', '1 Exhaust Fan', '2 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4.5 out of 5', 'Construction5 out ..."
4,4 BHK Flat in Sector 22 Gurgaon,flat,ambience creacions,sector 22,6.16,20533.0,3000.0,Carpet area: 3000 (278.71 sq.m.),4,5,3+,"pooja room,servant room","Sector 22 Gurgaon, Gurgaon, Haryana",10.0,South-East,0 to 1 Year Old,"['Moulsari Avenue', 'Ambience Mall', 'Old Delh...",Ambience creacions is one of gurgaon's most so...,"['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '4 Ge...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Lifestyle4 out of 5..."

In [153]:
# features to drop -> property_name, address, description, rating
df.drop(columns=['property_name', 'address', 'description', 'rating'],inplace=True)

In [154]:
df.sample(5)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
1444,flat,experion windchants,sector 112,3.75,13383.0,2802.0,Super Built up area 2802(260.31 sq.m.)Built Up...,3,3,2,servant room,21.0,West,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","['1 Water Purifier', '1 Exhaust Fan', '5 Geyse...","['Centrally Air Conditioned', 'Water purifier'..."
214,flat,chd avenue,sector 71,1.40,7945.0,1762.0,Carpet area: 1762 (163.7 sq.m.),3,3,2,pooja room,1.0,South-East,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...","['4 Wardrobe', '6 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Feng Shui / Vaastu ..."
963,flat,paras dews,sector 106,1.15,7419.0,1550.0,Super Built up area 1760(163.51 sq.m.)Built Up...,3,3,3,"servant room,pooja room",11.0,North-East,1 to 5 Year Old,"['MG Road Metro Station', 'NeoSquare Shopping ...","['4 Fan', '1 Exhaust Fan', '5 Light', '4 AC', ...","['Centrally Air Conditioned', 'Water purifier'..."
1161,flat,signature global park,sohna road,0.70,6071.0,1153.0,Carpet area: 1153 (107.12 sq.m.),3,3,3,pooja room,2.0,North,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","['3 Fan', '1 Exhaust Fan', '1 Dining Table', '...","['Centrally Air Conditioned', 'Water purifier'..."
919,house,unitech uniworld resorts,sector 33,9.50,173992.0,546.0,Plot area 546(50.73 sq.m.),6,6,3+,na,3.0,North-East,5 to 10 Year Old,"['Rajiv Chowk Mosque', 'Airforce Hospital', 'S...","['6 Wardrobe', '14 Fan', '1 Exhaust Fan', '7 G...","['Feng Shui / Vaastu Compliant', 'Maintenance ..."

In [157]:
df.shape

(3799, 17)

In [ ]:
# feature engineering required -> areaWithType, additionalRoom, facing, agePossession, furnishDetails, features

In [155]:
df.duplicated().sum()

np.int64(134)

In [156]:
df.to_csv('gurgaon_properties_cleaned_v1.csv',index=False)